
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 11;
  public static final int LT = 5;
  public static final int OVER = 12;
  public static final int ELSE = 26;
  public static final int PLUS = 9;
  public static final int NOTEQ = 4;
  public static final int INT = 30;
  public static final int RPAREN = 14;
  public static final int WHILE = 27;
  public static final int SEMI = 15;
  public static final int RSB = 20;
  public static final int RETURN = 29;
  public static final int ERROR = 31;
  public static final int IF = 25;
  public static final int LPAREN = 13;
  public static final int GT = 6;
  public static final int ID = 23;
  public static final int NUM = 24;
  public static final int LCB = 17;
  public static final int COMMA = 16;
  public static final int LTEQ = 8;
  public static final int EOF = 0;
  public static final int GE = 21;
  public static final int MINUS = 10;
  public static final int error = 1;
  public static final int RCB = 18;
  public static final int ASSIGN = 2;
  public static final int EQ = 3;
  public static final int GTEQ = 7;
  public static final int LSB = 19;
  public static final int VOID = 28;
  public static final int MUL = 22;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ASSIGN",
  "EQ",
  "NOTEQ",
  "LT",
  "GT",
  "GTEQ",
  "LTEQ",
  "PLUS",
  "MINUS",
  "TIMES",
  "OVER",
  "LPAREN",
  "RPAREN",
  "SEMI",
  "COMMA",
  "LCB",
  "RCB",
  "LSB",
  "RSB",
  "GE",
  "MUL",
  "ID",
  "NUM",
  "IF",
  "ELSE",
  "WHILE",
  "VOID",
  "RETURN",
  "INT",
  "ERROR"
  };
}

